
#define NN_SUCCESS 0

#define NN_ERR_MALLOC -1
#define NN_ERR_NOT_FOUND -2

#define NN_FAILED_TO_CREATE_NODE -11
#define NN_FAILED_TO_CREATE_EDGE -12
#define NN_FAILED_TO_CREATE_NODE_SOA -13
#define NN_FAILED_TO_CREATE_EDGE_SOA -14

#define NN_FAILED_TO_DELETE_NODE -21
#define NN_FAILED_TO_DELETE_EDGE -22
