// SPDX-License-Identifier: AGPL-3.0-only
// Copyright (C) 2026 Poyraz Bakırtaş

#define NN_SUCCESS 0

/// GENERAL ERRORS
#define NN_ERR_MALLOC -1
#define NN_ERR_NOT_FOUND -2

/// Create NODE/EDGE/NODE_SOA/EDGE_SOA ERRORS
#define NN_FAILED_TO_CREATE_NODE -11
#define NN_FAILED_TO_CREATE_EDGE -12
#define NN_FAILED_TO_CREATE_NODE_SOA -13
#define NN_FAILED_TO_CREATE_EDGE_SOA -14

/// DELETE NODE/EDGE ERRORS
#define NN_FAILED_TO_DELETE_NODE -21
#define NN_FAILED_TO_DELETE_EDGE -22

/// EVENT LIST ERRORS
#define NN_FAILED_TO_ADD_EVENT -31
#define NN_FAILED_TO_DELETE_EVENT -32
#define NN_FAILED_TO_CREATE_EVENT_LIST -33 
#define NN_FAILED_TO_DELETE_EVENT_LIST -34
#define NN_ERR_EVENT_LIST_CAPACITY -35
